services:
  database:
    container_name: database
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - backend_challenge

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - backend_challenge
    links:
      - database

  server:
    container_name: server
    image: server
    environment:
      - REDIS_URL=${REDIS_URL}
      - POSTGRES_URL=${POSTGRES_URL}
    networks:
      - backend_challenge
    ports:
      - 3000:3000
    links:
      - database
      - redis

networks:
  backend_challenge:
    name: backend_challenge
    driver: bridge

volumes:
  postgres-data:
  redis-data:
